version: "3.3"

services:
  redis:
    image: redis:6.2.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume_data:/data

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_volume_data:/db

volumes:
  redis_volume_data:
  redis_insight_volume_data:
